version: '3.3'
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  # dev:
  #   container_name: nestjs_api_dev
  #   image: nestjs-api-dev:1.0.0
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: npm run start:dev
  #   ports:
  #     - 4000:4000
  #     - 3001:9229
  #   networks:
  #     - nesjs-network
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  # prod:
  #   container_name: nestjs_api_prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 4000:4000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
